{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "pcnlwmtuzjhcrih4i3v4u2veyu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.2.1.aar",
          "url": "idnow-platform-4.2.1.aar",
          "size": 16607236,
          "sha512": "276343ec147904e29830bb814ecba35c1b247c003bd5ac2b94cc5655f3ed3e7b9e315b0c1e1f99635961d21f73babd60e2c63a6b5afbbffcdae554534a0b574c",
          "sha256": "a135e2f7ab157e523246490a447f55142a9d927069b9140947ccd00f0d36fb79",
          "sha1": "6c0f91143090db28357162f516d91573077c5dc0",
          "md5": "3ef9849569b327308e4c809456b77833"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.2.1.aar",
          "url": "idnow-platform-4.2.1.aar",
          "size": 16607236,
          "sha512": "276343ec147904e29830bb814ecba35c1b247c003bd5ac2b94cc5655f3ed3e7b9e315b0c1e1f99635961d21f73babd60e2c63a6b5afbbffcdae554534a0b574c",
          "sha256": "a135e2f7ab157e523246490a447f55142a9d927069b9140947ccd00f0d36fb79",
          "sha1": "6c0f91143090db28357162f516d91573077c5dc0",
          "md5": "3ef9849569b327308e4c809456b77833"
        }
      ]
    }
  ]
}
