{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "bi5j7n45jreclidlawqiargiae"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.0.0.aar",
          "url": "idnow-platform-4.0.0.aar",
          "size": 15875820,
          "sha512": "61ae8d75c87b53dcf41b0838ccc58e1e5d8fd50efb824afd8eb8fc2f58015093484d982cd28b5b868068286b025224ea51a7fffcb4865e11b9293b919b7cc9ee",
          "sha256": "a87d68cf89f02f10a20d3a7ce7688f1a2029aef59602c3d3687b88a6f99a92f3",
          "sha1": "e05eeb6431a79c5d6989866cf60c963a7b8efaa",
          "md5": "364016b5d7c0004827e774596a2d1d4c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.0.0.aar",
          "url": "idnow-platform-4.0.0.aar",
          "size": 15875820,
          "sha512": "61ae8d75c87b53dcf41b0838ccc58e1e5d8fd50efb824afd8eb8fc2f58015093484d982cd28b5b868068286b025224ea51a7fffcb4865e11b9293b919b7cc9ee",
          "sha256": "a87d68cf89f02f10a20d3a7ce7688f1a2029aef59602c3d3687b88a6f99a92f3",
          "sha1": "e05eeb6431a79c5d6989866cf60c963a7b8efaa",
          "md5": "364016b5d7c0004827e774596a2d1d4c"
        }
      ]
    }
  ]
}
