{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "2zcikh2mhbgx7nu4lagt6pyaky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "ch.acra",
          "module": "acra-core",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.10.0.aar",
          "url": "idnow-platform-4.10.0.aar",
          "size": 17616376,
          "sha512": "f7cd842f58d84047107b7d2bf144eb96f5f1fec8ca050e27049416d44ceac2b8ab4c5ffe9d26740c4072b15ca8f6f8af867f670a1f37d3c7b5c21e2be55c53ce",
          "sha256": "26ba96654715a53886bed7b1abbf5336e7fb6cc90e90d4b7a33799f8f84833c0",
          "sha1": "4bf7f46c894dd0f5a0b36000a5ff241717979fbe",
          "md5": "1a7ed84b74abc99eb4ffb75668b58045"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.10.0.aar",
          "url": "idnow-platform-4.10.0.aar",
          "size": 17616376,
          "sha512": "f7cd842f58d84047107b7d2bf144eb96f5f1fec8ca050e27049416d44ceac2b8ab4c5ffe9d26740c4072b15ca8f6f8af867f670a1f37d3c7b5c21e2be55c53ce",
          "sha256": "26ba96654715a53886bed7b1abbf5336e7fb6cc90e90d4b7a33799f8f84833c0",
          "sha1": "4bf7f46c894dd0f5a0b36000a5ff241717979fbe",
          "md5": "1a7ed84b74abc99eb4ffb75668b58045"
        }
      ]
    }
  ]
}
