{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qpn26jkhwzdjffb3qxawfpa5re"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.1.0.aar",
          "url": "idnow-platform-4.1.0.aar",
          "size": 15876594,
          "sha512": "1436b8439b206535aa842b0789894ac8230cefcbb382edcbcab7970e9859931a045de9ddcb5925323bdab100f92bd6517454e0da2d91b4af84f987a924f6fec0",
          "sha256": "3a3fa0a794032a532c857294998e22d924d973ad46f114293a847fe759851718",
          "sha1": "4c61498162e002d202825ae6668ec42fbf91a250",
          "md5": "375dc86b3ffb07a7b210d7d8ab627954"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.1.0.aar",
          "url": "idnow-platform-4.1.0.aar",
          "size": 15876594,
          "sha512": "1436b8439b206535aa842b0789894ac8230cefcbb382edcbcab7970e9859931a045de9ddcb5925323bdab100f92bd6517454e0da2d91b4af84f987a924f6fec0",
          "sha256": "3a3fa0a794032a532c857294998e22d924d973ad46f114293a847fe759851718",
          "sha1": "4c61498162e002d202825ae6668ec42fbf91a250",
          "md5": "375dc86b3ffb07a7b210d7d8ab627954"
        }
      ]
    }
  ]
}
