{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "o5g6nohzn5eodn3ci6ocf5oz4m"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.2.0.aar",
          "url": "idnow-platform-4.2.0.aar",
          "size": 16605490,
          "sha512": "ef3efc1cde83622c704a130bb392ba5583ee6133591a3ad8384b93439e80135ef4cf0743799f5b22be916d51949514d3e98b7ea02ddbb297e602c0aee7657d1e",
          "sha256": "4fc141d9e477253de4fb4e9f8051afbc7788c310d860497864a51d50c1981c76",
          "sha1": "e4d8cc5a904595f42822cb6619b72333ac40bff8",
          "md5": "bf0b470ae9db397e64b4dd3e4f2a42b6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.2.0.aar",
          "url": "idnow-platform-4.2.0.aar",
          "size": 16605490,
          "sha512": "ef3efc1cde83622c704a130bb392ba5583ee6133591a3ad8384b93439e80135ef4cf0743799f5b22be916d51949514d3e98b7ea02ddbb297e602c0aee7657d1e",
          "sha256": "4fc141d9e477253de4fb4e9f8051afbc7788c310d860497864a51d50c1981c76",
          "sha1": "e4d8cc5a904595f42822cb6619b72333ac40bff8",
          "md5": "bf0b470ae9db397e64b4dd3e4f2a42b6"
        }
      ]
    }
  ]
}
