{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "xkl7ueb3bfas7acnfqfhtimvw4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "ch.acra",
          "module": "acra-core",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.9.0.aar",
          "url": "idnow-platform-4.9.0.aar",
          "size": 17574784,
          "sha512": "bba1fe5eb5e92da55973b970e81810eb8cc9ac4096a2337c29c636e64823ada461c68a36718cf7a9521325b1e377c9289592478cb024e6e40e6582b3a8557bd6",
          "sha256": "991b264f052f261f337a368e03ebd702b4b6fd8dad8215508e4f6a4db3eb97bd",
          "sha1": "afa177610679b0877ed979c249b90f2ea5b99261",
          "md5": "cedd3ee664420964105f0cc318164931"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.9.0.aar",
          "url": "idnow-platform-4.9.0.aar",
          "size": 17574784,
          "sha512": "bba1fe5eb5e92da55973b970e81810eb8cc9ac4096a2337c29c636e64823ada461c68a36718cf7a9521325b1e377c9289592478cb024e6e40e6582b3a8557bd6",
          "sha256": "991b264f052f261f337a368e03ebd702b4b6fd8dad8215508e4f6a4db3eb97bd",
          "sha1": "afa177610679b0877ed979c249b90f2ea5b99261",
          "md5": "cedd3ee664420964105f0cc318164931"
        }
      ]
    }
  ]
}
