{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "cqjnlicd6vhdzf2dejfkoukv4m"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "ch.acra",
          "module": "acra-core",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.7.3.aar",
          "url": "idnow-platform-4.7.3.aar",
          "size": 17055023,
          "sha512": "f1a0d30c1f1490f1028fdeac85bf96a0687ea155e60c830f7923b08c4e3d23cd112b49616b0fdc9091bc3c2f9a1efbef781ff348257e42ce8c3087f353d8bf2e",
          "sha256": "f0fcbbf28acaf0499bd6bf3a68398e054b03ada09fdbca3fffbe2167f73fdace",
          "sha1": "e379d3e984b86224fb9c63ff05a794f43193f987",
          "md5": "7ddc64c1538302b201eeef685e8b3d37"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.7.3.aar",
          "url": "idnow-platform-4.7.3.aar",
          "size": 17055023,
          "sha512": "f1a0d30c1f1490f1028fdeac85bf96a0687ea155e60c830f7923b08c4e3d23cd112b49616b0fdc9091bc3c2f9a1efbef781ff348257e42ce8c3087f353d8bf2e",
          "sha256": "f0fcbbf28acaf0499bd6bf3a68398e054b03ada09fdbca3fffbe2167f73fdace",
          "sha1": "e379d3e984b86224fb9c63ff05a794f43193f987",
          "md5": "7ddc64c1538302b201eeef685e8b3d37"
        }
      ]
    }
  ]
}
