{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ffie3ujio5ap7f3rurmwuipsd4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "ch.acra",
          "module": "acra-core",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.7.2.aar",
          "url": "idnow-platform-4.7.2.aar",
          "size": 17055026,
          "sha512": "db438d7e6f3bdfb3b9f85ddd75f53ffad337ac3080de50bd6eeb43acfd6875f6e73e45b916c6c867aa3fe40b224eb5ef7bbae52d7ae9eba7e1ec8956947820a2",
          "sha256": "bfef0783f218b4698a9db14837f54b7403c42b684e82b9e27efe27ed3c43d1c4",
          "sha1": "e594932bd2bd4511e23850a9b9c036446672b9c",
          "md5": "10e07f0b565445f00e1f63619dd63ae9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.7.2.aar",
          "url": "idnow-platform-4.7.2.aar",
          "size": 17055026,
          "sha512": "db438d7e6f3bdfb3b9f85ddd75f53ffad337ac3080de50bd6eeb43acfd6875f6e73e45b916c6c867aa3fe40b224eb5ef7bbae52d7ae9eba7e1ec8956947820a2",
          "sha256": "bfef0783f218b4698a9db14837f54b7403c42b684e82b9e27efe27ed3c43d1c4",
          "sha1": "e594932bd2bd4511e23850a9b9c036446672b9c",
          "md5": "10e07f0b565445f00e1f63619dd63ae9"
        }
      ]
    }
  ]
}
