{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "vu5ratcitzaohpfqbk4lrdjr4y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "ch.acra",
          "module": "acra-core",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.7.2.aar",
          "url": "idnow-platform-4.7.2.aar",
          "size": 17069595,
          "sha512": "45ad007d6aacf8d6190e865592a9c9754216642f0c0ed9efcc6c180caf2fb896822e294039b1e96d0bda0beb0f54ec54b638aa3eba62c1f2076685009a354e60",
          "sha256": "e53f240835a9e8d42fe0d9c5eab0bcac95b0272cdabc92c3a44fe8a7ca2027cd",
          "sha1": "7cfcc9e1e500e7cc46a20c3a0fd770e916208310",
          "md5": "668a5958561fab837f47c09da9d68457"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.7.2.aar",
          "url": "idnow-platform-4.7.2.aar",
          "size": 17069595,
          "sha512": "45ad007d6aacf8d6190e865592a9c9754216642f0c0ed9efcc6c180caf2fb896822e294039b1e96d0bda0beb0f54ec54b638aa3eba62c1f2076685009a354e60",
          "sha256": "e53f240835a9e8d42fe0d9c5eab0bcac95b0272cdabc92c3a44fe8a7ca2027cd",
          "sha1": "7cfcc9e1e500e7cc46a20c3a0fd770e916208310",
          "md5": "668a5958561fab837f47c09da9d68457"
        }
      ]
    }
  ]
}
