{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "nxshsnpcxzd7lj6pzq33xrhrrm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "ch.acra",
          "module": "acra-core",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.8.0.aar",
          "url": "idnow-platform-4.8.0.aar",
          "size": 17505480,
          "sha512": "610cf3c32d8dc11c2bec5aaef6933033d38a8aef7c46918ef0f72a846777bd65c619bc6d6420c6745dea53110c5345b828f53925b4ed8db27da8087f7b202c8e",
          "sha256": "d8ea7feafe2a72630acf4babfac229cfbab05f18de6823e337e8946a0af30815",
          "sha1": "ee35777fa94d14646c025f51acc40b8c4dd9abe2",
          "md5": "c4824ca21683bb6668c1fde0d889a9dc"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.8.0.aar",
          "url": "idnow-platform-4.8.0.aar",
          "size": 17505480,
          "sha512": "610cf3c32d8dc11c2bec5aaef6933033d38a8aef7c46918ef0f72a846777bd65c619bc6d6420c6745dea53110c5345b828f53925b4ed8db27da8087f7b202c8e",
          "sha256": "d8ea7feafe2a72630acf4babfac229cfbab05f18de6823e337e8946a0af30815",
          "sha1": "ee35777fa94d14646c025f51acc40b8c4dd9abe2",
          "md5": "c4824ca21683bb6668c1fde0d889a9dc"
        }
      ]
    }
  ]
}
