{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "d6r4txxzifbmtbz4sjxnh2g2ny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.3.0.aar",
          "url": "idnow-platform-4.3.0.aar",
          "size": 16638375,
          "sha512": "a7e707276955fc0a12cf013b2e2418bdaf8e75edb2bd216f5be728a509b451ea2d4e7a1a1e752d30cf56d3a3c72ee67c59db1442791b481c7acc00dd078800f9",
          "sha256": "70b189376d135e6da8ee3483c7b29efe4f9aa2f44a1c446eaebdc65b9832a979",
          "sha1": "a0e5865a4058c74a29413d9873b038a382d741dd",
          "md5": "48d262b34f229ac2125d283f0eed766"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.3.0.aar",
          "url": "idnow-platform-4.3.0.aar",
          "size": 16638375,
          "sha512": "a7e707276955fc0a12cf013b2e2418bdaf8e75edb2bd216f5be728a509b451ea2d4e7a1a1e752d30cf56d3a3c72ee67c59db1442791b481c7acc00dd078800f9",
          "sha256": "70b189376d135e6da8ee3483c7b29efe4f9aa2f44a1c446eaebdc65b9832a979",
          "sha1": "a0e5865a4058c74a29413d9873b038a382d741dd",
          "md5": "48d262b34f229ac2125d283f0eed766"
        }
      ]
    }
  ]
}
