{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qr7es6byq5cybao3cs3eollyl4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "ch.acra",
          "module": "acra-core",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.12.0.aar",
          "url": "idnow-platform-4.12.0.aar",
          "size": 17729037,
          "sha512": "ad18d38ad2454af0fcf3dcfdce6f058defc289e1bb764decebd9b26a69009c392148868a6539e599f8dc5f90448d75c20d6645aeeeaa88964a3022bf465ed7e1",
          "sha256": "6ffca829b8d818f50e07d041e62b487a3b126129462128556d2968e7d3bfc4af",
          "sha1": "4af27a54caf30a15326f5f0e909d93b2c7b8ecea",
          "md5": "4790897bdfb84d65bd14abd2fc26f5c9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        },
        {
          "group": "de.idnow.insights",
          "module": "idnow-android-insights-sdk",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.12.0.aar",
          "url": "idnow-platform-4.12.0.aar",
          "size": 17729037,
          "sha512": "ad18d38ad2454af0fcf3dcfdce6f058defc289e1bb764decebd9b26a69009c392148868a6539e599f8dc5f90448d75c20d6645aeeeaa88964a3022bf465ed7e1",
          "sha256": "6ffca829b8d818f50e07d041e62b487a3b126129462128556d2968e7d3bfc4af",
          "sha1": "4af27a54caf30a15326f5f0e909d93b2c7b8ecea",
          "md5": "4790897bdfb84d65bd14abd2fc26f5c9"
        }
      ]
    }
  ]
}
