{
  "formatVersion": "1.1",
  "component": {
    "group": "de.idnow.android.sdk",
    "module": "idnow-platform",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "m2iaepds35bmhppxa6wlaa7lte"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "org.msgpack",
          "module": "jackson-dataformat-msgpack",
          "version": {
            "requires": "0.8.18"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "1.7.28"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.4.0.aar",
          "url": "idnow-platform-4.4.0.aar",
          "size": 16640134,
          "sha512": "e52ce5693c4e0895f3f56b7cb87798a4d93b0f6e3b913692456878be61eac8a2d50ec74b51650675b303846fff4bf943adf1d3c210764093c864fb63254907dc",
          "sha256": "63c4593138bd8c3645527e29265ce628a1d49721f3acfe02ee1760b6857ba287",
          "sha1": "ef96eeaf30df3981f9a8e60a6b747e8fffbf79",
          "md5": "13f25483e437ac86882b0df73d299f6d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "idnow-platform-4.4.0.aar",
          "url": "idnow-platform-4.4.0.aar",
          "size": 16640134,
          "sha512": "e52ce5693c4e0895f3f56b7cb87798a4d93b0f6e3b913692456878be61eac8a2d50ec74b51650675b303846fff4bf943adf1d3c210764093c864fb63254907dc",
          "sha256": "63c4593138bd8c3645527e29265ce628a1d49721f3acfe02ee1760b6857ba287",
          "sha1": "ef96eeaf30df3981f9a8e60a6b747e8fffbf79",
          "md5": "13f25483e437ac86882b0df73d299f6d"
        }
      ]
    }
  ]
}
